/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 03:31:08 PM CDT 
//


package com.cts.cip.common.model.kpi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LabelsCreated complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LabelsCreated">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="total" type="{http://www.cognizant.com/retail/cip/TotalReqRecivedResponse}SimpleCount"/>
 *         &lt;element name="carriers" type="{http://www.cognizant.com/retail/cip/TotalReqRecivedResponse}CountByCarriers"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabelsCreated", namespace = "http://www.cognizant.com/retail/cip/TotalReqRecivedResponse", propOrder = {
    "total",
    "carriers"
})
@XmlRootElement(name = "LabelsCreated")
public class LabelsCreated {

    @XmlElement(namespace = "http://www.cognizant.com/retail/cip/TotalReqRecivedResponse", required = true)
    protected SimpleCount total;
    @XmlElement(namespace = "http://www.cognizant.com/retail/cip/TotalReqRecivedResponse", required = true)
    protected CountByCarriers carriers;

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleCount }
     *     
     */
    public SimpleCount getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleCount }
     *     
     */
    public void setTotal(SimpleCount value) {
        this.total = value;
    }

    /**
     * Gets the value of the carriers property.
     * 
     * @return
     *     possible object is
     *     {@link CountByCarriers }
     *     
     */
    public CountByCarriers getCarriers() {
        return carriers;
    }

    /**
     * Sets the value of the carriers property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountByCarriers }
     *     
     */
    public void setCarriers(CountByCarriers value) {
        this.carriers = value;
    }

}
