/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.10 at 10:50:39 AM CDT 
//


package com.cts.cip.common.model.kpi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SUKPIFilterCriteria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SUKPIFilterCriteria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dateTimeRange" type="{http://www.cognizant.com/retail/cip/KPIGenericCriteria}DateTimeRange"/>
 *         &lt;element name="businessUnits" type="{http://www.cognizant.com/retail/cip/KPIGenericCriteria}BusinessUnitList" minOccurs="0"/>
 *         &lt;element name="carriers" type="{http://www.cognizant.com/retail/cip/KPIGenericCriteria}CarrierList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SUKPIFilterCriteria", namespace = "http://www.cognizant.com/retail/cip/KPIGenericCriteria", propOrder = {
    "dateTimeRange",
    "businessUnits",
    "carriers"
})
public class SUKPIFilterCriteria {

    @XmlElement(namespace = "http://www.cognizant.com/retail/cip/KPIGenericCriteria", required = true)
    protected DateTimeRange dateTimeRange;
    @XmlElement(namespace = "http://www.cognizant.com/retail/cip/KPIGenericCriteria")
    protected BusinessUnitList businessUnits;
    @XmlElement(namespace = "http://www.cognizant.com/retail/cip/KPIGenericCriteria")
    protected CarrierList carriers;

    /**
     * Gets the value of the dateTimeRange property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeRange }
     *     
     */
    public DateTimeRange getDateTimeRange() {
        return dateTimeRange;
    }

    /**
     * Sets the value of the dateTimeRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeRange }
     *     
     */
    public void setDateTimeRange(DateTimeRange value) {
        this.dateTimeRange = value;
    }

    /**
     * Gets the value of the businessUnits property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessUnitList }
     *     
     */
    public BusinessUnitList getBusinessUnits() {
        return businessUnits;
    }

    /**
     * Sets the value of the businessUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessUnitList }
     *     
     */
    public void setBusinessUnits(BusinessUnitList value) {
        this.businessUnits = value;
    }

    /**
     * Gets the value of the carriers property.
     * 
     * @return
     *     possible object is
     *     {@link CarrierList }
     *     
     */
    public CarrierList getCarriers() {
        return carriers;
    }

    /**
     * Sets the value of the carriers property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarrierList }
     *     
     */
    public void setCarriers(CarrierList value) {
        this.carriers = value;
    }

}
