/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.10 at 10:50:39 AM CDT 
//


package com.cts.cip.common.model.kpi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimelineDataUnit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimelineDataUnit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xValue1">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-999999999"/>
 *               &lt;maxInclusive value="999999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="yValue" type="{http://www.cognizant.com/retail/cip/KPIGenericCriteria}DateTimeRange"/>
 *         &lt;element name="yCaption" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimelineDataUnit", namespace = "http://www.cognizant.com/retail/cip/PendingManifest", propOrder = {
    "xValue",
    "yValue",
    "xCaption"
})
public class TimelineDataUnit {

    @XmlElement(namespace = "http://www.cognizant.com/retail/cip/PendingManifest")
    protected int yValue;
    @XmlElement(namespace = "http://www.cognizant.com/retail/cip/PendingManifest", required = true)
    protected DateTimeRange xValue;
    @XmlElement(namespace = "http://www.cognizant.com/retail/cip/PendingManifest")
    protected String xCaption;

    /**
     * Gets the value of the xValue1 property.
     * 
     */
    public int getXValue1() {
        return yValue;
    }

    /**
     * Sets the value of the xValue1 property.
     * 
     */
    public void setXValue1(int value) {
        this.yValue = value;
    }

    /**
     * Gets the value of the yValue property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeRange }
     *     
     */
    public DateTimeRange getYValue() {
        return xValue;
    }

    /**
     * Sets the value of the yValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeRange }
     *     
     */
    public void setYValue(DateTimeRange value) {
        this.xValue = value;
    }

    /**
     * Gets the value of the yCaption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYCaption() {
        return xCaption;
    }

    /**
     * Sets the value of the yCaption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYCaption(String value) {
        this.xCaption = value;
    }

}
