/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
package com.cts.cip.carrier;

import com.cts.cip.agent.model.CancelRequest;
import com.cts.cip.agent.model.CancelResponse;
import com.cts.cip.agent.model.CreateRequest;
import com.cts.cip.agent.model.CreateResponse;
import com.cts.cip.agent.model.TrackRequest;
import com.cts.cip.agent.model.TrackResponse;
import com.cts.cip.carrier.exception.CarrierClientException;

public interface CarrierShipment {
	
	/**
	 * Process the COM Request to register / Create Shipment Request with Carrier
	 * @param createShipmentRequest
	 * @param trackingNumber
	 * @return
	 * @throws CarrierClientException
	 */
	public CreateResponse createCarrierShipment(CreateRequest createShipmentRequest,String trackingNumber) throws CarrierClientException;
	

	/**
	 * Method to retrieve Tracking Number .Could be pulled from a pool or generated by Carrier real time
	 * @param createShipmentRequest
	 * @return
	 * @throws CarrierClientException
	 */
	public String getTrackingNumber(CreateRequest createShipmentRequest) throws CarrierClientException;

	/**
	 * Method to delete/cancel a shipment
	 * @param cancelRequest
	 * @return
	 */
	public CancelResponse cancelCarrierShipment(CancelRequest cancelRequest);

	/**
	 * Method to track a Shipment
	 * @param trackRequest
	 * @return
	 * @throws CarrierClientException
	 */
	public TrackResponse trackCarrierShipment(TrackRequest trackRequest) throws CarrierClientException;
	
}
