/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 10:27:10 AM CDT 
//


package com.cts.cip.common.model;

import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;


/**
 * <p>Java class for address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="address">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="individualName" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="companyName" type="{http://www.cts.com/cip/Common}stringType" minOccurs="0"/>
 *         &lt;element name="addressLine1" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="addressLine2" type="{http://www.cts.com/cip/Common}stringType" minOccurs="0"/>
 *         &lt;element name="addressLine3" type="{http://www.cts.com/cip/Common}stringType" minOccurs="0"/>
 *         &lt;element name="addressLine4" type="{http://www.cts.com/cip/Common}stringType" minOccurs="0"/>
 *         &lt;element name="city" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="state" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="country" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="countryCode" type="{http://www.cts.com/cip/Common}countryCode"/>
 *         &lt;element name="zipCode" type="{http://www.cts.com/cip/Common}zipCodeType"/>
 *         &lt;element name="phoneNumber" type="{http://www.cts.com/cip/Common}phoneNumberType" minOccurs="0"/>
 *         &lt;element name="faxNumber" type="{http://www.cts.com/cip/Common}phoneNumberType" minOccurs="0"/>
 *         &lt;element name="emailAddress" type="{http://www.cts.com/cip/Common}emailAddressType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "address", propOrder = {
    "individualName",
    "companyName",
    "addressLine1",
    "addressLine2",
    "addressLine3",
    "addressLine4",
    "city",
    "state",
    "country",
    "countryCode",
    "zipCode",
    "phoneNumber",
    "faxNumber",
    "emailAddress"
})
public class Address {

    @XmlElement(required = true)
    @NotBlank(message = "{cip_common.shippingunit.address.individualname.empty}")
    @Pattern(regexp = "^[A-Za-z0-9\\s\\-\\.\\,\\_*]+$", 
	message="{cip_common.shippingunit.address.individualname.pattern}")
    @Size(min = 0, max = 35,  message = "{cip_common.shippingunit.address.individualname.size}")
    protected String individualName;
    
    @Pattern(regexp = "^[A-Za-z0-9\\s\\-\\.\\_*]+$", 
    	message="{cip_common.shippingunit.address.companyname.pattern}")
    @Size(min = 0, max = 35,  message = "{cip_common.shippingunit.address.companyname.size}")
    protected String companyName;
    
    @XmlElement(required = true)
    @NotBlank(message = "{cip_common.shippingunit.address.addressline1.empty}")
    @Pattern(regexp = "^[A-Za-z0-9\\s\\-\\_\\.\\#\\*]+$", 
	message="{cip_common.shippingunit.address.addressline1.pattern}")
    @Size(min = 0, max = 35,  message = "{cip_common.shippingunit.address.addressline1.size}")
    protected String addressLine1;
    
    @Pattern(regexp = "^[A-Za-z0-9\\s\\-\\_\\.\\#\\*]+$", 
    		message="{cip_common.shippingunit.address.addressline2.pattern}")
    @Size(min = 0, max = 35,  message = "{cip_common.shippingunit.address.addressline2.size}")
    protected String addressLine2;
    
    @Pattern(regexp = "^[A-Za-z0-9\\s\\-\\_\\.\\#\\*]+$", 
    		message="{cip_common.shippingunit.address.addressline3.pattern}")
    @Size(min = 0, max = 35,  message = "{cip_common.shippingunit.address.addressline3.size}")
    protected String addressLine3;
    
    @Pattern(regexp = "^[A-Za-z0-9\\s\\-\\_\\.\\#\\*]+$", 
    		message="{cip_common.shippingunit.address.addressline4.pattern}")
    @Size(min = 0, max = 35,  message = "{cip_common.shippingunit.address.addressline4.size}")
    protected String addressLine4;
    
    @XmlElement(required = true)
    //NEED TO RE LOOK
    //@NotBlank(message = "{cip_common.shippingunit.address.city.empty}")
    @Pattern(regexp = "^[A-Za-z0-9\\s]+$", 
		message="{cip_common.shippingunit.address.city.pattern}")
    @Size(min = 0, max = 35,  message = "{cip_common.shippingunit.address.city.size}")
    protected String city;
    
    
    
    //NEED TO RE LOOK
    //@NotBlank(message = "{cip_common.shippingunit.address.state.empty}")
    @Pattern(regexp = "^[A-Za-z0-9\\s\\-\\_\\.\\#\\*]+$", 
	message="{cip_common.shippingunit.address.state.pattern}")
    @Size(min = 0, max = 35,  message = "{cip_common.shippingunit.address.state.size}")
    protected String state;
    

    @NotBlank(message = "{cip_common.shippingunit.address.country.empty}")
    @Pattern(regexp = "^[A-Za-z0-9\\s\\-\\_\\.\\#\\*]+$", 
   		message="{cip_common.shippingunit.address.country.pattern}")
    @Size(min = 0, max = 20,  message = "{cip_common.shippingunit.address.country.size}")
    protected String country;
    
    @XmlElement(required = true, defaultValue = "US")
    protected CountryCode countryCode;
    

    @NotBlank(message = "{cip_common.shippingunit.address.zipcode.empty}")
    @Pattern(regexp = "^[A-Za-z0-9\\s\\-\\_\\.\\#\\*]+$", 
	message="{cip_common.shippingunit.address.zipcode.pattern}")
    @Size(min = 0, max = 10,  message = "{cip_common.shippingunit.address.zipcode.size}")
    protected String zipCode;
    
    //@NotBlank(message = "{cip_common.shippingunit.address.phonenumber.empty}")
    @Pattern(regexp = "^[0-9]+$", 
	message="{cip_common.shippingunit.address.phonenumber.pattern}")
    @Size(min = 0, max = 10,  message = "{cip_common.shippingunit.address.phonenumber.size}")
    protected String phoneNumber;
    
   
    @Pattern(regexp = "^[0-9]+$", 
	message="{cip_common.shippingunit.address.faxnumber.pattern}")
    @Size(min = 0, max = 10,  message = "{cip_common.shippingunit.address.faxnumber.size}")
    protected String faxNumber;
    
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    @Email(message = "{cip_common.shippingunit.address.emailaddress.invalid}")
    @Size(min = 0, max = 50,  message = "{cip_common.shippingunit.address.emailaddress.size}")
    protected String emailAddress;

    /**
     * Gets the value of the individualName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualName() {
        return individualName;
    }

    /**
     * Sets the value of the individualName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualName(String value) {
        this.individualName = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the addressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * Sets the value of the addressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine1(String value) {
        this.addressLine1 = value;
    }

    /**
     * Gets the value of the addressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * Sets the value of the addressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine2(String value) {
        this.addressLine2 = value;
    }

    /**
     * Gets the value of the addressLine3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine3() {
        return addressLine3;
    }

    /**
     * Sets the value of the addressLine3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine3(String value) {
        this.addressLine3 = value;
    }

    /**
     * Gets the value of the addressLine4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine4() {
        return addressLine4;
    }

    /**
     * Sets the value of the addressLine4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine4(String value) {
        this.addressLine4 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCode }
     *     
     */
    public CountryCode getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCode }
     *     
     */
    public void setCountryCode(CountryCode value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the faxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxNumber() {
        return faxNumber;
    }

    /**
     * Sets the value of the faxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxNumber(String value) {
        this.faxNumber = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

}
