/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 10:27:10 AM CDT 
//


package com.cts.cip.common.model;

import java.util.ArrayList;
import java.util.List;

import javax.validation.Valid;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for invoiceDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invoiceDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.cts.com/cip/Common}intType"/>
 *         &lt;element name="salesTax" type="{http://www.cts.com/cip/Common}price"/>
 *         &lt;element name="shippingAndHandlingCharges" type="{http://www.cts.com/cip/Common}price"/>
 *         &lt;element name="totalOrderItemsCost" type="{http://www.cts.com/cip/Common}price"/>
 *         &lt;element name="shipmentTotalCost" type="{http://www.cts.com/cip/Common}price"/>
 *         &lt;element name="items" type="{http://www.cts.com/cip/CreateShippingUnitRequest}item" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoiceDetails", namespace = "http://www.cts.com/cip/CreateShippingUnitRequest", propOrder = {
    "id",
    "salesTax",
    "shippingAndHandlingCharges",
    "totalOrderItemsCost",
    "shipmentTotalCost",
    "items"
})
public class InvoiceDetails {

    protected int id;
    
    @XmlElement(required = true)
    @Valid
    protected Price salesTax;
    
    @XmlElement(required = true)
    @Valid
    protected Price shippingAndHandlingCharges;
    
    @XmlElement(required = true)
    @Valid
    protected Price totalOrderItemsCost;
    
    @XmlElement(required = true)
    @Valid
    protected Price shipmentTotalCost;
    
    @XmlElement(required = true)
    @Valid
    protected List<Item> items;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the salesTax property.
     * 
     * @return
     *     possible object is
     *     {@link Price }
     *     
     */
    public Price getSalesTax() {
        return salesTax;
    }

    /**
     * Sets the value of the salesTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Price }
     *     
     */
    public void setSalesTax(Price value) {
        this.salesTax = value;
    }

    /**
     * Gets the value of the shippingAndHandlingCharges property.
     * 
     * @return
     *     possible object is
     *     {@link Price }
     *     
     */
    public Price getShippingAndHandlingCharges() {
        return shippingAndHandlingCharges;
    }

    /**
     * Sets the value of the shippingAndHandlingCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Price }
     *     
     */
    public void setShippingAndHandlingCharges(Price value) {
        this.shippingAndHandlingCharges = value;
    }

    /**
     * Gets the value of the totalOrderItemsCost property.
     * 
     * @return
     *     possible object is
     *     {@link Price }
     *     
     */
    public Price getTotalOrderItemsCost() {
        return totalOrderItemsCost;
    }

    /**
     * Sets the value of the totalOrderItemsCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Price }
     *     
     */
    public void setTotalOrderItemsCost(Price value) {
        this.totalOrderItemsCost = value;
    }

    /**
     * Gets the value of the shipmentTotalCost property.
     * 
     * @return
     *     possible object is
     *     {@link Price }
     *     
     */
    public Price getShipmentTotalCost() {
        return shipmentTotalCost;
    }

    /**
     * Sets the value of the shipmentTotalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Price }
     *     
     */
    public void setShipmentTotalCost(Price value) {
        this.shipmentTotalCost = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the items property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Item }
     * 
     * 
     */
    public List<Item> getItems() {
        if (items == null) {
            items = new ArrayList<Item>();
        }
        return this.items;
    }

}
