/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.22 at 07:51:18 PM CDT 
//


package com.cts.cip.common.model;

import javax.validation.Valid;
import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for loadBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="loadBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.cts.com/cip/Common}intType" minOccurs="0"/>
 *         &lt;element name="loadReferenceId" type="{http://www.cts.com/cip/Common}stringType" minOccurs="0"/>
 *         &lt;element name="loadTrailerNumber" type="{http://www.cts.com/cip/Common}trailerNumber" minOccurs="0"/>
 *         &lt;element name="carrierloadTrailerNumber" type="{http://www.cts.com/cip/Common}carrierTrailerNumber" minOccurs="0"/>
 *         &lt;element name="distributionCenterID" type="{http://www.cts.com/cip/Common}distributionCenterID" minOccurs="0"/>
 *         &lt;element name="carrierID" type="{http://www.cts.com/cip/Common}carrierID" minOccurs="0"/>
 *         &lt;element name="carrierName" type="{http://www.cts.com/cip/Common}carrierName" minOccurs="0"/>
 *         &lt;element name="totalUnitCount" type="{http://www.cts.com/cip/Common}totalUnitCount" minOccurs="0"/>
 *         &lt;element name="totalUnitWeight" type="{http://www.cts.com/cip/Common}totalUnitWeight" minOccurs="0"/>
 *         &lt;element name="loadState" type="{http://www.cts.com/cip/Common}loadState" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loadBase", propOrder = {
    "id",
    "loadReferenceId",
    "loadTrailerNumber",
    "carrierloadTrailerNumber",
    "distributionCenterID",
    "carrierID",
    "carrierName",
    "totalUnitCount",
    "totalUnitWeight",
    "loadState"
})
public class LoadBase {
	
	
    protected Integer id;
	
	@NotNull(message="{cip_common.loadbase.loadreferenceid.empty}")
	@Pattern(regexp = "^[A-Za-z0-9]+$", message="{cip_common.loadbase.loadreferenceid.pattern}")
    @Size(min = 0, max = 25,  message = "{cip_common.loadbase.loadreferenceid.maxlength}")
    protected String loadReferenceId;
	
	@Pattern(regexp = "^[A-Za-z0-9\\s\\-]+$", message="{cip_common.loadbase.loadtrailernumber.pattern}")
    @Size(min = 0, max = 25,  message = "{cip_common.loadbase.loadtrailernumber.maxlength}")
    protected String loadTrailerNumber;
	
	@Pattern(regexp = "^[A-Za-z0-9\\s\\-]+$", message="{cip_common.loadbase.carrierloadtrailernumber.pattern}")
    @Size(min = 0, max = 25,  message = "{cip_common.loadbase.carrierloadtrailernumber.maxlength}")
    protected String carrierloadTrailerNumber;
	
	@Max(value = 999999999, message = "{cip_common.loadbase.distributioncenterid.maxlimit}")
	@Min(value = 0, message = "{cip_common.loadbase.distributioncenterid.minlimit}")
	@Digits(integer=9, fraction=0,  message = "{cip_common.loadbase.distributioncenterid.size}" )
    protected Integer distributionCenterID;
	
	@Pattern(regexp = "^[A-Za-z0-9\\s]+$", message="{cip_common.loadbase.carrierid.pattern}")
    @Size(min = 0, max = 13,  message = "{cip_common.loadbase.carrierid.maxlength}")
    protected String carrierID;
	
	@Pattern(regexp = "^[A-Za-z0-9\\s]+$", message="{cip_common.loadbase.carrierName.pattern}")
    @Size(min = 0, max = 45,  message = "{cip_common.loadbase.carrierName.maxlength}")
    protected String carrierName;
	
	@DecimalMax(value = "999999999", message = "{cip_common.loadbase.totalunitcount.maxlimit}")
	@DecimalMin(value = "0", message = "{cip_common.loadbase.totalunitcount.minlimit}")
	@Digits(integer=9, fraction=0,  message = "{cip_common.loadbase.totalunitcount.size}" )
    protected Integer totalUnitCount;
	
	@Valid
    protected TotalUnitWeight totalUnitWeight;
	
	
    @XmlSchemaType(name = "string")
    protected LoadState loadState;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the loadReferenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadReferenceId() {
        return loadReferenceId;
    }

    /**
     * Sets the value of the loadReferenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadReferenceId(String value) {
        this.loadReferenceId = value;
    }

    /**
     * Gets the value of the loadTrailerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadTrailerNumber() {
        return loadTrailerNumber;
    }

    /**
     * Sets the value of the loadTrailerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadTrailerNumber(String value) {
        this.loadTrailerNumber = value;
    }

    /**
     * Gets the value of the carrierloadTrailerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierloadTrailerNumber() {
        return carrierloadTrailerNumber;
    }

    /**
     * Sets the value of the carrierloadTrailerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierloadTrailerNumber(String value) {
        this.carrierloadTrailerNumber = value;
    }

    /**
     * Gets the value of the distributionCenterID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDistributionCenterID() {
        return distributionCenterID;
    }

    /**
     * Sets the value of the distributionCenterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDistributionCenterID(Integer value) {
        this.distributionCenterID = value;
    }

    /**
     * Gets the value of the carrierID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierID() {
        return carrierID;
    }

    /**
     * Sets the value of the carrierID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierID(String value) {
        this.carrierID = value;
    }

    /**
     * Gets the value of the totalUnitCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalUnitCount() {
        return totalUnitCount;
    }

    /**
     * Sets the value of the totalUnitCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalUnitCount(Integer value) {
        this.totalUnitCount = value;
    }

    /**
     * Gets the value of the totalUnitWeight property.
     * 
     * @return
     *     possible object is
     *     {@link TotalUnitWeight }
     *     
     */
    public TotalUnitWeight getTotalUnitWeight() {
        return totalUnitWeight;
    }

    /**
     * Sets the value of the totalUnitWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalUnitWeight }
     *     
     */
    public void setTotalUnitWeight(TotalUnitWeight value) {
        this.totalUnitWeight = value;
    }

    /**
     * Gets the value of the loadState property.
     * 
     * @return
     *     possible object is
     *     {@link LoadState }
     *     
     */
    public LoadState getLoadState() {
        return loadState;
    }

    /**
     * Sets the value of the loadState property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadState }
     *     
     */
    public void setLoadState(LoadState value) {
        this.loadState = value;
    }

	/**
	 * @return the carrierName
	 */
	public String getCarrierName() {
		return carrierName;
	}

	/**
	 * @param carrierName the carrierName to set
	 */
	public void setCarrierName(String carrierName) {
		this.carrierName = carrierName;
	}

}
