/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 10:27:10 AM CDT 
//


package com.cts.cip.common.model;

import javax.validation.Valid;
import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for order complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="order">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderNumber" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="poNumber" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="customerMembershipNumber" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="distributionCenterID" type="{http://www.cts.com/cip/Common}distributionCenterID"/>
 *         &lt;element name="businessUnitID" type="{http://www.cts.com/cip/Common}intType"/>
 *         &lt;element name="trailerNumber" type="{http://www.cts.com/cip/Common}trailerNumber" minOccurs="0"/>
 *         &lt;element name="carrierTrailerNumber" type="{http://www.cts.com/cip/Common}carrierTrailerNumber" minOccurs="0"/>
 *         &lt;element name="trasactionControlNumber" type="{http://www.cts.com/cip/Common}stringType" minOccurs="0"/>
 *         &lt;element name="datePlannedShipment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="waveNumber" type="{http://www.cts.com/cip/Common}intType" minOccurs="0"/>
 *         &lt;element name="asnNumber" type="{http://www.cts.com/cip/Common}stringType" minOccurs="0"/>
 *         &lt;element name="shippingOptions" type="{http://www.cts.com/cip/CreateShippingUnitRequest}shippingOptions" minOccurs="0"/>
 *         &lt;element name="billingAddress" type="{http://www.cts.com/cip/Common}address" minOccurs="0"/>
 *         &lt;element name="deliveryToAddress" type="{http://www.cts.com/cip/Common}address" minOccurs="0"/>
 *         &lt;element name="returnAddress" type="{http://www.cts.com/cip/Common}address"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "order", namespace = "http://www.cts.com/cip/CreateShippingUnitRequest", propOrder = {
    "orderNumber",
    "poNumber",
    "customerMembershipNumber",
    "distributionCenterID",
    "businessUnitID",
    "trailerNumber",
    "carrierTrailerNumber",
    "trasactionControlNumber",
    "datePlannedShipment",
    "waveNumber",
    "asnNumber",
    "shippingOptions",
    "billingAddress",
    "deliveryToAddress",
    "returnAddress"
})
public class Order {

    @XmlElement(required = true)
    @Pattern(regexp = "^[0-9]+$", 
   	message="{cip_common.shippingunit.order.ordernumber.pattern}")
    @Size(min = 0, max = 20,  message = "{cip_common.shippingunit.order.ordernumber.size}")
    protected String orderNumber;
    
    @XmlElement(required = true)
    @Pattern(regexp = "^[0-9]+$", 
   	message="{cip_common.shippingunit.order.ponumber.pattern}")
    @Size(min = 0, max = 40,  message = "{cip_common.shippingunit.order.ponumber.size}")
    protected String poNumber;
    
    @XmlElement(required = true)
    @Pattern(regexp = "^[0-9]+$", message="{cip_common.shippingunit.order.customer.membershipnumber.pattern}")
    @Size(min = 0, max = 14,  message="{cip_common.shippingunit.order.customer.membershipnumber.size}")
    protected String customerMembershipNumber;
    
    @Digits(integer=9, fraction=0,  message = "{cip_common.shippingunit.order.distributionCenterID.size}" )
   // @Size(min = 0, max = 9,  message =  "{cip_common.shippingunit.order.distributionCenterID.size}")
    protected int distributionCenterID;
    @Digits(integer=9, fraction=0,  message = "{cip_common.shippingunit.order.businessUnitID.size}" ) 
    //@Size(min = 0, max = 9,  message =  "{cip_common.shippingunit.order.businessUnitID.size}")
    protected int businessUnitID;
    
    @Pattern(regexp = "^[A-Za-z0-9\\s\\-\\_\\.\\#\\*]+$", 
    	   	message="{cip_common.shippingunit.order.trailernumber.pattern}")
    @Size(min = 0, max = 25,  message = "{cip_common.shippingunit.order.trailernumber.size}")
    protected String trailerNumber;
    
    @Pattern(regexp = "^[A-Za-z0-9\\s\\-\\_\\.\\#\\*]+$", 
    	   	message="{cip_common.shippingunit.order.carriertrailernumber.pattern}")
    @Size(min = 0, max = 25,  message = "{cip_common.shippingunit.order.carriertrailernumber.size}")
    protected String carrierTrailerNumber;
    
    @Pattern(regexp = "^[A-Za-z0-9\\s\\-\\_\\.\\#\\*]+$", 
    	   	message="{cip_common.shippingunit.order.tcnumber.pattern}")
    	    @Size(min = 0, max = 25,  message = "{cip_common.shippingunit.order.tcnumber.size}")
    protected String trasactionControlNumber;
    
    @Pattern(regexp = "^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$", 
    	   	message="{cip_common.shippingunit.order.dateplannedshipment.pattern}")
    @Size(min = 0, max = 16,  message = "{cip_common.shippingunit.order.dateplannedshipment.size}")
    protected String datePlannedShipment;
    
    @Pattern(regexp = "^[0-9]+$",message="{cip_common.shippingunit.order.waveNumber.pattern}")
    @Size(min = 1, max = 9,  message = "{cip_common.shippingunit.order.waveNumber.size}")
    protected String waveNumber;
    
    
    @Pattern(regexp = "^[A-Za-z0-9\\.\\-\\_*]+$",message="{cip_common.shippingunit.order.asnnumber.pattern}")
    @Size(min = 0, max = 25,  message = "{cip_common.shippingunit.order.asnnumber.size}")
    protected String asnNumber;
    
    @Valid
    protected ShippingOptions shippingOptions;
    
    @Valid
    protected Address billingAddress;
    @Valid
    protected Address deliveryToAddress;
    @XmlElement(required = true)
    @Valid
    protected Address returnAddress;

    /**
     * Gets the value of the orderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * Sets the value of the orderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNumber(String value) {
        this.orderNumber = value;
    }

    /**
     * Gets the value of the poNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoNumber() {
        return poNumber;
    }

    /**
     * Sets the value of the poNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoNumber(String value) {
        this.poNumber = value;
    }

    /**
     * Gets the value of the customerMembershipNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerMembershipNumber() {
        return customerMembershipNumber;
    }

    /**
     * Sets the value of the customerMembershipNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerMembershipNumber(String value) {
        this.customerMembershipNumber = value;
    }

    /**
     * Gets the value of the distributionCenterID property.
     * 
     */
    public int getDistributionCenterID() {
        return distributionCenterID;
    }

    /**
     * Sets the value of the distributionCenterID property.
     * 
     */
    public void setDistributionCenterID(int value) {
        this.distributionCenterID = value;
    }

    /**
     * Gets the value of the businessUnitID property.
     * 
     */
    public int getBusinessUnitID() {
        return businessUnitID;
    }

    /**
     * Sets the value of the businessUnitID property.
     * 
     */
    public void setBusinessUnitID(int value) {
        this.businessUnitID = value;
    }

    /**
     * Gets the value of the trailerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrailerNumber() {
        return trailerNumber;
    }

    /**
     * Sets the value of the trailerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrailerNumber(String value) {
        this.trailerNumber = value;
    }

    /**
     * Gets the value of the carrierTrailerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierTrailerNumber() {
        return carrierTrailerNumber;
    }

    /**
     * Sets the value of the carrierTrailerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierTrailerNumber(String value) {
        this.carrierTrailerNumber = value;
    }

    /**
     * Gets the value of the trasactionControlNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrasactionControlNumber() {
        return trasactionControlNumber;
    }

    /**
     * Sets the value of the trasactionControlNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrasactionControlNumber(String value) {
        this.trasactionControlNumber = value;
    }

    /**
     * Gets the value of the datePlannedShipment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatePlannedShipment() {
        return datePlannedShipment;
    }

    /**
     * Sets the value of the datePlannedShipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatePlannedShipment(String value) {
        this.datePlannedShipment = value;
    }

    /**
     * Gets the value of the waveNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public String getWaveNumber() {
        return waveNumber;
    }

    /**
     * Sets the value of the waveNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWaveNumber(String value) {
        this.waveNumber = value;
    }

    /**
     * Gets the value of the asnNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsnNumber() {
        return asnNumber;
    }

    /**
     * Sets the value of the asnNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsnNumber(String value) {
        this.asnNumber = value;
    }

    /**
     * Gets the value of the shippingOptions property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingOptions }
     *     
     */
    public ShippingOptions getShippingOptions() {
        return shippingOptions;
    }

    /**
     * Sets the value of the shippingOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingOptions }
     *     
     */
    public void setShippingOptions(ShippingOptions value) {
        this.shippingOptions = value;
    }

    /**
     * Gets the value of the billingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getBillingAddress() {
        return billingAddress;
    }

    /**
     * Sets the value of the billingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setBillingAddress(Address value) {
        this.billingAddress = value;
    }

    /**
     * Gets the value of the deliveryToAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getDeliveryToAddress() {
        return deliveryToAddress;
    }

    /**
     * Sets the value of the deliveryToAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setDeliveryToAddress(Address value) {
        this.deliveryToAddress = value;
    }

    /**
     * Gets the value of the returnAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getReturnAddress() {
        return returnAddress;
    }

    /**
     * Sets the value of the returnAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setReturnAddress(Address value) {
        this.returnAddress = value;
    }

}
