/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 10:27:10 AM CDT 
//


package com.cts.cip.common.model;

import java.util.HashMap;
import java.util.Map;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import org.hibernate.validator.constraints.Length;


/**
 * <p>Java class for shippingUnitBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="shippingUnitBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.cts.com/cip/Common}intType"/>
 *         &lt;element name="transactionId" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="referenceID" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="description" type="{http://www.cts.com/cip/Common}stringType" minOccurs="0"/>
 *         &lt;element name="state" type="{http://www.cts.com/cip/Common}shippingUnitState" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.cts.com/cip/Common}shippingUnitType" default="CARTON" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "shippingUnitBase", propOrder = {
    "id",
    "transactionId",
    "referenceID",
    "description",
    "state"
})
public class ShippingUnitBase {

	
    protected int id;
    
    @Pattern(regexp = "^[0-9a-zA-Z]+$", message="{cip_common.shippingunit.shippingunitbase.transactionId.pattern}")
    @Size(min = 0, max = 30,  message = "{cip_common.shippingunit.shippingunitbase.transactionId.maxlength}")
    @XmlElement(required = true)
    protected String transactionId;
    
    @XmlElement(required = true)
    @NotNull
    @Pattern(regexp = "^[a-zA-Z0-9]+$", message="{cip_common.shippingunit.shippingunitbase.referenceID.pattern}")
    @Size(min = 0, max = 20, message = "{cip_common.shippingunit.shippingunitbase.referenceID.maxlength}")
    protected String referenceID;
    
    @Pattern(regexp = "^[A-Za-z0-9\\s\\@\\#\\$\\%\\^\\&\\(\\)\\[\\]\\{\\}\\\\^\\$\\|\\?\\*\\+\\.\\<\\>\\-\\=\\!\\_\\,\\*]+$", 
    		message="{cip_common.shippingunit.shippingunitbase.description.pattern}")
    @Size(min = 0, max = 100, message = "{cip_common.shippingunit.shippingunitbase.description.maxlength}")
    protected String description;
    
    @XmlSchemaType(name = "string")
    protected ShippingUnitState state;
    @XmlAttribute(name = "type", namespace = "http://www.cts.com/cip/Common")
    protected ShippingUnitType type;
    
	@XmlTransient
    protected String postalBarCode;
	@XmlTransient
	protected String maxiCode;
	@XmlTransient
	protected String routingCode;
	@XmlTransient
	protected String version;
	@XmlTransient
	protected String versionDate;
	@XmlTransient
	protected String trackingNumber;
	
	@XmlTransient
	protected String packageWeight;
	@XmlTransient
	protected String packageWeightUOM;
	@XmlTransient
	protected String isMaxiCodeReqd;
	@XmlTransient
	protected String serviceName;
	
	@XmlTransient
	protected String serviceIcon_p1;
	@XmlTransient
	protected String serviceIcon_p2;
	@XmlTransient
	protected String serviceIcon_p3;
	
	
	@XmlTransient
	protected String propertyOne;
	@XmlTransient
	protected String propertyTwo;
	@XmlTransient
	protected String propertyThree;
	@XmlTransient
	protected String propertyFour;
	@XmlTransient
	protected String propertyFive;
	@XmlTransient
	protected String propertySix;
	@XmlTransient
	protected String propertySeven;
	@XmlTransient
	protected String propertyEight;
	@XmlTransient
	protected String propertyNine;
	@XmlTransient
	protected String propertyTen;

	
	
	@XmlTransient
	protected KeyValuePair[] labelParameters;


    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the referenceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceID() {
        return referenceID;
    }

    /**
     * Sets the value of the referenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceID(String value) {
        this.referenceID = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingUnitState }
     *     
     */
    public ShippingUnitState getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingUnitState }
     *     
     */
    public void setState(ShippingUnitState value) {
        this.state = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingUnitType }
     *     
     */
    public ShippingUnitType getType() {
        if (type == null) {
            return ShippingUnitType.CARTON;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingUnitType }
     *     
     */
    public void setType(ShippingUnitType value) {
        this.type = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "ShippingUnitBase [id=" + id + ", transactionId=" + transactionId + ", referenceID=" + referenceID
				+ ", description=" + description + ", state=" + state + ", type=" + type + "]";
	}
    
	

	public KeyValuePair[] getLabelParameters() {
		return labelParameters;
	}

	public void setLabelParameters(KeyValuePair[] labelParameters) {
		this.labelParameters = labelParameters;
	}

	public String getPostalBarCode() {
		return postalBarCode;
	}

	public void setPostalBarCode(String postalBarCode) {
		this.postalBarCode = postalBarCode;
	}

	public String getMaxiCode() {
		return maxiCode;
	}

	public void setMaxiCode(String maxiCode) {
		this.maxiCode = maxiCode;
	}

	public String getRoutingCode() {
		return routingCode;
	}

	public void setRoutingCode(String routingCode) {
		this.routingCode = routingCode;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getVersionDate() {
		return versionDate;
	}

	public void setVersionDate(String versionDate) {
		this.versionDate = versionDate;
	}

	public String getTrackingNumber() {
		return trackingNumber;
	}

	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	public String getPackageWeight() {
		return packageWeight;
	}

	public void setPackageWeight(String packageWeight) {
		this.packageWeight = packageWeight;
	}

	public String getPackageWeightUOM() {
		return packageWeightUOM;
	}

	public void setPackageWeightUOM(String packageWeightUOM) {
		this.packageWeightUOM = packageWeightUOM;
	}

	public String isMaxiCodeReqd() {
		return isMaxiCodeReqd;
	}

	public void setMaxiCodeReqd(String isMaxiCodeReqd) {
		this.isMaxiCodeReqd = isMaxiCodeReqd;
	}

	public String getServiceName() {
		return serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public String getServiceIcon_p1() {
		return serviceIcon_p1;
	}

	public void setServiceIcon_p1(String serviceIcon_p1) {
		this.serviceIcon_p1 = serviceIcon_p1;
	}

	public String getServiceIcon_p2() {
		return serviceIcon_p2;
	}

	public void setServiceIcon_p2(String serviceIcon_p2) {
		this.serviceIcon_p2 = serviceIcon_p2;
	}

	public String getServiceIcon_p3() {
		return serviceIcon_p3;
	}

	public void setServiceIcon_p3(String serviceIcon_p3) {
		this.serviceIcon_p3 = serviceIcon_p3;
	}

	public String getPropertyOne() {
		return propertyOne;
	}

	public void setPropertyOne(String propertyOne) {
		this.propertyOne = propertyOne;
	}

	public String getPropertyTwo() {
		return propertyTwo;
	}

	public void setPropertyTwo(String propertyTwo) {
		this.propertyTwo = propertyTwo;
	}

	public String getPropertyThree() {
		return propertyThree;
	}

	public void setPropertyThree(String propertyThree) {
		this.propertyThree = propertyThree;
	}

	public String getPropertyFour() {
		return propertyFour;
	}

	public void setPropertyFour(String propertyFour) {
		this.propertyFour = propertyFour;
	}

	public String getPropertyFive() {
		return propertyFive;
	}

	public void setPropertyFive(String propertyFive) {
		this.propertyFive = propertyFive;
	}

	public String getPropertySix() {
		return propertySix;
	}

	public void setPropertySix(String propertySix) {
		this.propertySix = propertySix;
	}

	public String getPropertySeven() {
		return propertySeven;
	}

	public void setPropertySeven(String propertySeven) {
		this.propertySeven = propertySeven;
	}

	public String getPropertyEight() {
		return propertyEight;
	}

	public void setPropertyEight(String propertyEight) {
		this.propertyEight = propertyEight;
	}

	public String getPropertyNine() {
		return propertyNine;
	}

	public void setPropertyNine(String propertyNine) {
		this.propertyNine = propertyNine;
	}

	public String getPropertyTen() {
		return propertyTen;
	}

	public void setPropertyTen(String propertyTen) {
		this.propertyTen = propertyTen;
	}
       
    

}
