/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 10:27:10 AM CDT 
//


package com.cts.cip.common.model;

import javax.validation.Valid;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shippingOptions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="shippingOptions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="specialServiceType" type="{http://www.cts.com/cip/CreateShippingUnitRequest}specialService" minOccurs="0"/>
 *         &lt;element name="specialInstructions" type="{http://www.cts.com/cip/Common}stringType" minOccurs="0"/>
 *         &lt;element name="hazardousMaterial" type="{http://www.cts.com/cip/CreateShippingUnitRequest}hazardousMaterial" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "shippingOptions", namespace = "http://www.cts.com/cip/CreateShippingUnitRequest", propOrder = {
    "specialServiceType",
    "specialInstructions",
    "hazardousMaterial"
})
public class ShippingOptions {

    @XmlSchemaType(name = "string")
    protected SpecialService specialServiceType;
    
    @Pattern(regexp = "^[A-Za-z0-9\\s\\(\\)\\[\\]\\{\\}\\\\^\\$\\|\\?\\*\\+\\.\\<\\>\\-\\=\\!\\_\\,\\*]+$", 
    	   	message="{cip_common.shippingunit.order.options.specialinstructions.pattern}")
    @Size(min = 0, max = 150,  message = "{cip_common.shippingunit.order.options.specialinstructions.size}")
    protected String specialInstructions;
    
    @Valid
    protected HazardousMaterial hazardousMaterial;

    /**
     * Gets the value of the specialServiceType property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialService }
     *     
     */
    public SpecialService getSpecialServiceType() {
        return specialServiceType;
    }

    /**
     * Sets the value of the specialServiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialService }
     *     
     */
    public void setSpecialServiceType(SpecialService value) {
        this.specialServiceType = value;
    }

    /**
     * Gets the value of the specialInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialInstructions() {
        return specialInstructions;
    }

    /**
     * Sets the value of the specialInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialInstructions(String value) {
        this.specialInstructions = value;
    }

    /**
     * Gets the value of the hazardousMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link HazardousMaterial }
     *     
     */
    public HazardousMaterial getHazardousMaterial() {
        return hazardousMaterial;
    }

    /**
     * Sets the value of the hazardousMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link HazardousMaterial }
     *     
     */
    public void setHazardousMaterial(HazardousMaterial value) {
        this.hazardousMaterial = value;
    }

}
