/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 10:27:10 AM CDT 
//


package com.cts.cip.common.model;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shipperDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="shipperDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="billingAccountID" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="meterID" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="shipperServiceType" type="{http://www.cts.com/cip/CreateShippingUnitRequest}shipperServiceType"/>
 *         &lt;element name="shipperAddress" type="{http://www.cts.com/cip/Common}address" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "shipperDetails", namespace = "http://www.cts.com/cip/CreateShippingUnitRequest", propOrder = {
    "billingAccountID",
    "meterID",
    "shipperServiceType",
    "shipperAddress"
})
public class ShipperDetails {

    
    @Pattern(regexp = "^[0-9]+$", message="{cip_common.shippingunit.shipperdetails.billingaccountid.pattern}")
    @Size(min = 0, max = 25,  message = "{cip_common.shippingunit.shipperdetails.billingaccountid.maxlength}")
    @NotNull
    protected String billingAccountID;
    
    
    @Pattern(regexp = "^[0-9]+$", message="{cip_common.shippingunit.shipperdetails.meterid.pattern}")
    @Size(min = 0, max = 25,  message = "{cip_common.shippingunit.shipperdetails.meterid.maxlength}")
    protected String meterID;
    
    @XmlElement(required = true)
    @NotNull
    @Valid
    protected ShipperServiceType shipperServiceType;
    @NotNull
    @Valid
    protected Address shipperAddress;

    /**
     * Gets the value of the billingAccountID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAccountID() {
        return billingAccountID;
    }

    /**
     * Sets the value of the billingAccountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAccountID(String value) {
        this.billingAccountID = value;
    }

    /**
     * Gets the value of the meterID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterID() {
        return meterID;
    }

    /**
     * Sets the value of the meterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterID(String value) {
        this.meterID = value;
    }

    /**
     * Gets the value of the shipperServiceType property.
     * 
     * @return
     *     possible object is
     *     {@link ShipperServiceType }
     *     
     */
    public ShipperServiceType getShipperServiceType() {
        return shipperServiceType;
    }

    /**
     * Sets the value of the shipperServiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipperServiceType }
     *     
     */
    public void setShipperServiceType(ShipperServiceType value) {
        this.shipperServiceType = value;
    }

    /**
     * Gets the value of the shipperAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getShipperAddress() {
        return shipperAddress;
    }

    /**
     * Sets the value of the shipperAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setShipperAddress(Address value) {
        this.shipperAddress = value;
    }

}
