/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 10:27:10 AM CDT 
//


package com.cts.cip.common.model;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shipperServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="shipperServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="shipperServiceTypeID" type="{http://www.cts.com/cip/Common}intType"/>
 *         &lt;element name="shipperServiceTypeCode" type="{http://www.cts.com/cip/Common}stringType"/>
 *         &lt;element name="shipperServiceTypeName" type="{http://www.cts.com/cip/Common}stringType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "shipperServiceType", namespace = "http://www.cts.com/cip/CreateShippingUnitRequest", propOrder = {
    "shipperServiceTypeID",
    "shipperServiceTypeCode",
    "shipperServiceTypeName"
})
public class ShipperServiceType {
	
	@NotNull(message = "{cip_common.shippingunit.shipperdetails.shipperservicetype.shipperservicetypeid.empty}")
	@Pattern(regexp = "^\\d*$", 
	message="{cip_common.shippingunit.shipperdetails.shipperservicetype.shipperservicetypeid.pattern}")
	@Size(min = 0, max = 9,  message = "{cip_common.shippingunit.shipperdetails.shipperservicetype.shipperservicetypeid.size}")
    protected String shipperServiceTypeID;
	
    @XmlElement(required = true)
	@NotNull(message = "{cip_common.shippingunit.shipperdetails.shipperservicetype.shipperservicetypecode.empty}")
	@Pattern(regexp = "^[A-Za-z0-9\\s\\.\\-\\_]+$",  
	message="{cip_common.shippingunit.shipperdetails.shipperservicetype.shipperservicetypecode.pattern}")
	@Size(min = 0, max = 10,  message = "{cip_common.shippingunit.shipperdetails.shipperservicetype.shipperservicetypecode.size}")
    protected String shipperServiceTypeCode;
    
    @Pattern(regexp = "^[A-Za-z0-9\\s\\.\\-\\_*]+$", 
    		message="{cip_common.shippingunit.shipperdetails.shipperservicetype.shipperservicetypename.pattern}")
    @Size(min = 0, max = 25,  message = "{cip_common.shippingunit.shipperdetails.shipperservicetype.shipperservicetypename.limit}")
    protected String shipperServiceTypeName;

    /**
     * Gets the value of the shipperServiceTypeID property.
     * 
     */
    public String getShipperServiceTypeID() {
        return shipperServiceTypeID;
    }

    /**
     * Sets the value of the shipperServiceTypeID property.
     * 
     */
    public void setShipperServiceTypeID(String value) {
        this.shipperServiceTypeID = value;
    }

    /**
     * Gets the value of the shipperServiceTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipperServiceTypeCode() {
        return shipperServiceTypeCode;
    }

    /**
     * Sets the value of the shipperServiceTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipperServiceTypeCode(String value) {
        this.shipperServiceTypeCode = value;
    }

    /**
     * Gets the value of the shipperServiceTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipperServiceTypeName() {
        return shipperServiceTypeName;
    }

    /**
     * Sets the value of the shipperServiceTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipperServiceTypeName(String value) {
        this.shipperServiceTypeName = value;
    }

}
