/*******************************************************************************
 * (C) Copyright 2016 Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *  
 *   Contributors:
 *       Cognizant Worldwide Limited (fka, CTS UK Ltd) (“CWW”)
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 10:27:10 AM CDT 
//


package com.cts.cip.common.model;

import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for totalUnitWeight complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="totalUnitWeight">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unitWeight" type="{http://www.cts.com/cip/Common}decType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="weightUOM" type="{http://www.cts.com/cip/Common}weightUOM" default="LBS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "totalUnitWeight", propOrder = {
    "unitWeight"
})
public class TotalUnitWeight {

	@DecimalMax(value = "999.99", message = "{cip_common.loadbase.totalunitweight.unitweight.maxlimit}")
    @DecimalMin(value = "0.0", message = "{cip_common.loadbase.totalunitweight.unitweight.minlimit}")
    protected float unitWeight;
	
    @XmlAttribute(name = "weightUOM", namespace = "http://www.cts.com/cip/Common")
    protected WeightUOM weightUOM;

    /**
     * Gets the value of the unitWeight property.
     * 
     */
    public float getUnitWeight() {
        return unitWeight;
    }

    /**
     * Sets the value of the unitWeight property.
     * 
     */
    public void setUnitWeight(float value) {
        this.unitWeight = value;
    }

    /**
     * Gets the value of the weightUOM property.
     * 
     * @return
     *     possible object is
     *     {@link WeightUOM }
     *     
     */
    public WeightUOM getWeightUOM() {
        if (weightUOM == null) {
            return WeightUOM.LBS;
        } else {
            return weightUOM;
        }
    }

    /**
     * Sets the value of the weightUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightUOM }
     *     
     */
    public void setWeightUOM(WeightUOM value) {
        this.weightUOM = value;
    }

}
